Repository framgia/sph-ut-uni-charts, pull requests merged in 2022-05, with the labels that each got.

#15 UniChart: Create a function that will filter the list in the backend
  backlog/controllers/ProviderController.ts
  backlog/index.ts
  backlog/models/Provider.ts
  backlog/test/controllers/BacklogController.test.ts
  backlog/test/controllers/ProviderController.test.ts
  backlog/test/models/ProviderModel.test.ts
  bff/src/controllers/ProviderController.ts
  bff/src/routes/ProviderRoute.ts
  bff/src/services/BacklogService.ts
Labels: Approved by Nielmar, approved by joshua

#21 Google Login Integration
  bff/src/controllers/AccountController.ts
  fe/.env.local.example
  fe/__tests__/index.test.js
  fe/__tests__/login.test.js
  fe/package.json
  fe/pages/_app.js
  fe/pages/contexts/AuthContextProvider.js
  fe/pages/login.js
  fe/src/api/authApi.js
  fe/src/api/base.js
  fe/src/components/molecules/Loader/Loader.js
  fe/src/components/molecules/Loader/Loader.module.css
  fe/src/components/molecules/Loader/package.json
  fe/src/components/molecules/Navbar/Navbar.js
  fe/src/components/molecules/Navbar/Navbar.module.css
  fe/src/components/molecules/Navbar/package.json
  fe/src/const/routes.json
  fe/src/pages/index.js
  fe/src/pages/login/index.js
  fe/src/services/authService.js
  fe/src/templates/AuthMiddleware.js
  fe/yarn.lock
Labels: Approved by Nielmar, Approved by Chevy

#17 Create Function that will Remove the Project
  .vscode/settings.json
  backlog/controllers/ProjectController.ts
  backlog/routes/ProjectRoute.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/routes/ProjectRoute.test.ts
  backlog/yarn.lock
  bff/src/controllers/ProjectController.ts
  bff/src/routes/ProjectRoute.ts
  bff/src/services/BacklogService.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/routes/ProjectRoute.test.ts
  bff/src/test/services/BacklogService.test.ts
Labels: For Code Review, For QA Review

#24 Create API to fetch ET and submitted ET for sprint
  bff/package.json
  bff/src/controllers/IssueController.ts
  bff/src/controllers/ProjectController.ts
  bff/src/routes/ProjectRoute.ts
  bff/src/services/BacklogService.ts
  bff/yarn.lock
  fe/src/pages/projects/ProjectDetail.js
  fe/src/services/bffService.js
  fe/src/utils/helpers.js
Labels: Approved by Nielmar, approved by joshua

#27 Add test cases for velocity chart task BE changes.
  backlog/controllers/ProviderController.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/controllers/ProviderController.test.ts
  backlog/test/routes/ProjectRoute.test.ts
  backlog/test/routes/ProviderRoute.test.ts
  bff/jest.config.js
  bff/jest.setup.ts
  bff/package.json
  bff/src/controllers/IssueController.ts
  bff/src/services/BacklogService.ts
  bff/src/test/constants/issueTestData.json
  bff/src/test/controllers/IssueController.test.ts
  bff/src/test/services/BacklogService.test.ts
  bff/src/utils/interfaces.ts
  bff/tsconfig.json
Labels: Approved by Nielmar, Approved By Zion, approved by joshua

#23 Homepage
  backlog/controllers/ProjectController.ts
  backlog/models/interfaces/Project.ts
  backlog/test/const/project.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/controllers/ProviderController.test.ts
  bff/src/controllers/ProjectController.ts
  bff/src/services/BacklogService.ts
  bff/yarn.lock
  fe/__tests__/constants/testData.json
  fe/__tests__/index.test.js
  fe/__tests__/login.test.js
  fe/__tests__/snapshot.test.js
  fe/package.json
  fe/src/pages/index.js
  fe/src/pages/login/index.js
  fe/src/services/authService.js
  fe/src/services/bffService.js
  fe/src/templates/AuthMiddleware.js
  fe/yarn.lock
Labels: Approved by Nielmar, Approved by Alvil

#30 Feature/fix refactor backlog service
  backlog/controllers/BacklogController.ts
  backlog/controllers/ProviderController.ts
  backlog/index.ts
  backlog/models/Provider.ts
  backlog/package.json
  backlog/test/const/project.ts
  backlog/test/controllers/BacklogController.test.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/controllers/ProviderController.test.ts
  backlog/test/interfaces/response.ts
  backlog/test/models/ProviderModel.test.ts
  backlog/test/routes/ProjectRoute.test.ts
  backlog/test/routes/ProviderRoute.test.ts
  backlog/validations/ProviderValidation.ts
  backlog/yarn.lock
Labels: Approved by Nielmar

#29 Integrate remove project.
  backlog/controllers/ProjectController.ts
  backlog/test/controllers/ProjectController.test.ts
  bff/src/controllers/ProjectController.ts
  bff/src/services/BacklogService.ts
  bff/src/test/constants/projectTestData.json
  bff/src/test/controllers/IssueController.test.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/routes/ProjectRoute.test.ts
  bff/src/test/services/BacklogService.test.ts
  bff/src/utils/interfaces.ts
  fe/__tests__/index.test.js
  fe/__tests__/project-detail.test.js
  fe/src/components/molecules/DeleteModal/index.js
  fe/src/components/organisms/HomePageDeleteModal/HomePageDeleteModal.module.css
  fe/src/components/organisms/HomePageDeleteModal/index.js
  fe/src/pages/index.js
  fe/src/services/bffService.js
Labels: Approved by Nielmar

#31 [Bug Fix] Input filter by project name field is not reset if user didn't tap `enter key` and then reset Filter.
  fe/src/pages/index.js
Labels: Approved by Paul

#32 [Bug Fix] Unable to display Project list again if user open the project details and then go back to home page again.
  backlog/controllers/ProjectController.ts
  backlog/test/controllers/ProjectController.test.ts
  bff/src/controllers/IssueController.ts
  bff/src/controllers/ProjectController.ts
  bff/src/services/BacklogService.ts
  bff/src/test/controllers/IssueController.test.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/routes/ProjectRoute.test.ts
  bff/src/test/services/BacklogService.test.ts
Labels: Approved by Nielmar

#33 [BugFix]Unable to select project from the dropdown list for first click.
  fe/src/pages/projects/AddProject.js
Labels: Approved by Paul
