Repository framgia/sph-ut-uni-charts, pull requests merged in 2022-04, with the labels that each got.

#3 UniChart: Create migration for provider and project
  account/prisma/migrations/20220418065824_update_user_columns/migration.sql
  account/prisma/schema.prisma
  backlog/prisma/migrations/20220418072804_add_provider_and_project_table/migration.sql
  backlog/prisma/schema.prisma
Labels: Nielmar is reviewing

#4 UniChart: Modify provider and project table
  backlog/prisma/migrations/20220419033008_modify_provider_and_project_table/migration.sql
  backlog/prisma/schema.prisma
Labels: Approved by Nielmar

#5 Create Markup for the Add Project Page
  fe/__tests__/add-project.test.js
  fe/jest.setup.js
  fe/pages/add-project.js
  fe/src/pages/projects/AddProject.js
  fe/src/pages/projects/components/FormProvider.js
  fe/src/pages/projects/components/PageActions.js
  fe/src/pages/projects/components/PageTitle.js
  fe/src/pages/projects/components/index.js
  fe/styles/add-project.module.css
Labels: For Code Review, Approved by Nielmar, approved by joshua

#7 Create markup for home page.
  fe/__tests__/__snapshots__/snapshot.test.js.snap
  fe/__tests__/index.test.js
  fe/__tests__/snapshot.test.js
  fe/jest.setup.js
  fe/src/pages/index.js
  fe/src/utils/constants.js
  fe/src/utils/dummyData.js
  fe/styles/index.module.css
Labels: Approved by Nielmar, Approved By Zion

#8 Prepare Docker
  .dockerignore
  Dockerfile
  README.md
  account/.gitignore
  account/index.js
  account/package-lock.json
  account/yarn-error.log
  account/yarn.lock
  backlog/.gitignore
  backlog/controllers/test.js
  backlog/index.js
  backlog/package-lock.json
  backlog/yarn-error.log
  backlog/yarn.lock
  bff/.gitignore
  bff/package-lock.json
  bff/src/controller/test.js
  bff/src/index.js
  bff/src/services/BaseService.js
  bff/yarn-error.log
  bff/yarn.lock
  clockify/.gitignore
  clockify/index.js
  clockify/package-lock.json
  clockify/yarn-error.log
  clockify/yarn.lock
  docker-compose.yml
  docker/docker-compose.yml
  scripts/boot.sh
Labels: Approved by Nielmar, code approved

#6 UniChart: Create a function search for specific project
  backlog/controllers/ProjectController.ts
  backlog/controllers/test.js
  backlog/package.json
  backlog/routes/ProjectRoute.ts
  backlog/routes/ProviderRoute.ts
  backlog/routes/test.js
  backlog/test/Index.test.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/controllers/ProviderController.test.ts
  backlog/test/models/ProviderModel.test.ts
  backlog/test/routes/ProjectRoute.test.ts
  backlog/yarn-error.log
  backlog/yarn.lock
  bff/jest.config.js
  bff/nodemon.json
  bff/package.json
  bff/src/controller/test.js
  bff/src/controller/user.js
  bff/src/controllers/ProjectController.ts
  bff/src/controllers/ProviderController.ts
  bff/src/index.js
  bff/src/index.ts
  bff/src/routes/ProjectRoute.ts
  bff/src/routes/Provider.js
  bff/src/routes/ProviderRoute.ts
  bff/src/routes/test.js
  bff/src/routes/user.js
  bff/src/services/Backlog.js
  bff/src/services/BacklogService.ts
  bff/src/services/BaseService.js
  bff/src/services/BaseService.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/index.test.js
  bff/src/test/index.test.ts
  bff/src/test/routes/ProjectRoute.test.ts
  bff/src/test/services/BacklogService.test.ts
  bff/tsconfig.json
  bff/yarn.lock
Labels: Nielmar is reviewing, Code Reviewing

#12 Create project detail page markup.
  fe/__tests__/project-detail.test.js
  fe/jest.setup.js
  fe/package.json
  fe/pages/project-detail/[id].js
  fe/src/pages/projects/AddProject.js
  fe/src/pages/projects/ProjectDetail.js
  fe/src/pages/projects/components/Chart.js
  fe/src/pages/projects/components/PageTitle.js
  fe/src/pages/projects/components/index.js
  fe/src/utils/constants.js
  fe/src/utils/dummyData.js
  fe/src/utils/helpers.js
  fe/styles/project-detail.module.css
  fe/yarn.lock
Labels: Approved by Nielmar, Approved By Zion

#19 Create webhook and update Backlog Issue
  clockify/controllers/WebhookController.ts
  clockify/index.js
  clockify/index.ts
  clockify/jest.config.js
  clockify/package.json
  clockify/routes/base.ts
  clockify/routes/index.ts
  clockify/routes/test.ts
  clockify/test/controllers/WebhookController.test.ts
  clockify/tsconfig.json
  clockify/yarn.lock
Labels: Approved by Nielmar
