Repository framgia/sph-ut-uni-charts, pull requests merged in 2022-06, with the labels that each got.

#35 Get current logged in user_id
  account/controllers/UserController.ts
  account/index.ts
  account/package.json
  account/routes/userRoute.ts
  account/test/controller/user.test.ts
  account/validations/UserValdiation.js
  account/yarn.lock
  backlog/controllers/BacklogController.ts
  backlog/controllers/ProjectController.ts
  backlog/controllers/ProviderController.ts
  backlog/interfaces/Project.ts
  backlog/interfaces/Provider.ts
  backlog/models/Provider.ts
  backlog/models/interfaces/Provider.ts
  backlog/prisma/migrations/20220526072802_alter_project_table_add_user_id_column/migration.sql
  backlog/prisma/schema.prisma
  backlog/test/const/project.ts
  backlog/test/controllers/BacklogController.test.ts
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/models/ProviderModel.test.ts
  bff/package.json
  bff/src/controllers/AccountController.ts
  bff/src/controllers/BacklogController.ts
  bff/src/controllers/Controller.ts
  bff/src/controllers/IssueController.ts
  bff/src/controllers/ProjectController.ts
  bff/src/controllers/ProviderController.ts
  bff/src/routes/AccountRoute.ts
  bff/src/routes/ProviderRoute.ts
  bff/src/services/AccountService.ts
  bff/src/services/BacklogService.ts
  bff/src/test/controllers/IssueController.test.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/routes/BacklogService.test.ts
  bff/src/test/routes/ProjectRoute.test.ts
  bff/src/utils/interfaces.ts
  bff/yarn.lock
  fe/.env.local.example
  fe/src/api/authApi.js
  fe/src/api/base.js
  fe/src/api/providerApi.js
  fe/src/pages/index.js
  fe/src/pages/login/index.js
  fe/src/pages/projects/AddProject.js
  fe/src/pages/projects/ProjectDetail.js
  fe/src/services/bffService.js
Labels: Approved by Nielmar, approved by joshua

#34 Feature/add pagination
  Dockerfile
  backlog/controllers/ProjectController.ts
  backlog/interfaces/Project.ts
  backlog/jest.config.js
  backlog/models/Project.ts
  backlog/package.json
  backlog/test/controllers/ProjectController.test.ts
  backlog/test/utils/customMatcher.ts
  backlog/utils/Paginator.ts
  bff/src/test/routes/BacklogService.test.ts
  fe/__tests__/constants/testData.json
  fe/__tests__/index.test.js
  fe/__tests__/index/delete-project.test.js
  fe/__tests__/index/filter.test.js
  fe/__tests__/index/pagination.test.js
  fe/__tests__/index/sign-out.test.js
  fe/next.config.js
  fe/src/components/molecules/TableList/index.js
  fe/src/components/organisms/TopBar.js
  fe/src/pages/index.js
  fe/src/templates/Main.js
  fe/styles/index.module.css
Labels: Approved by Nielmar

#28 Unit Tests for Burn-down Chart Feature
  bff/src/controllers/Controller.ts
  bff/src/controllers/IssueController.ts
  bff/src/controllers/ProjectController.ts
  bff/src/services/BacklogService.ts
  bff/src/test/constants/projectTestData.json
  bff/src/test/controllers/IssueController.test.ts
  bff/src/test/controllers/ProjectController.test.ts
  bff/src/test/routes/BacklogService.test.ts
  bff/src/utils/helpers.ts
  fe/__tests__/project-detail.test.js
  fe/src/pages/projects/ProjectDetail.js
  fe/src/utils/helpers.js
Labels: Approved by Chevy, Approved by John Harvey

#38 FE unit test warning fixes
  fe/__tests__/add-project.test.js
Labels: Approved by Paul
